### ISSUE TITLE
Invalid Absolute URLs are treated as relative

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#26]
Similar to #18, but the following config:

```yml
  - id: npci-cts-circulars
    title: cts Circulars
    description: NPCI CTS Circulars
    url: "https://www.npci.org.in/what-we-do/cts/circulars"
    item_selector: '#year2020 .pdf-item'
    item_description_selector: p
    item_link_selector: a:nth-child(1)
    item_title_selector: p:nth-child(2)
```

gets me the following feed item:

```xml
    <item>
      <title><![CDATA[Circular no.38 Active - Active Set up(DEM) - All]]></title>
      <link>https://www.npci.org.in/what-we-do/cts/circulars/PDF/cts/Circular no.38 Active - Active Set up%28DEM%29.pdf</link>
      
      <description><![CDATA[Circular no.38 Active - Active Set up(DEM) - All]]></description>
      <content:encoded><![CDATA[Circular no.38 Active - Active Set up(DEM) - All]]></content:encoded>
      <guid isPermaLink="true">https://www.npci.org.in/what-we-do/cts/circulars/PDF/cts/Circular no.38 Active - Active Set up%28DEM%29.pdf</guid>
      
    </item>
```

from the following HTML:

```html
<div class="pdf-item">
                        <div class="pdf">
                            <img src="/images/npci/pdf.svg">
                        </div>
                        <p>Circular no.38 Active - Active Set up(DEM) - All</p>
                        <div class="download">
                            <a target="_blank" href="/PDF/cts/Circular no.38 Active - Active Set up%28DEM%29.pdf">READ
                                <img src="/images/npci/readiicon.png"> </a>
                        </div>
                        <div class="download">
                            <a target="_blank" href="/PDF/cts/Circular no.38 Active - Active Set up%28DEM%29.pdf" download="">DOWNLOAD <img src="/images/npci/down-arrow.svg"> </a>
                        </div>
                    </div>
```

The `link` tag should be pointing to `https://www.npci.org.in/PDF/cts/Circular%20no.38%20Active%20-%20Active%20Set%20up%28DEM%29.pdf` instead of `https://www.npci.org.in/what-we-do/cts/circulars/PDF/cts/Circular no.38 Active - Active Set up%28DEM%29.pdf`
