### ISSUE TITLE
Support YAML Aliases

### ISSUE THREAD

**Issue by captn3m0** [r7kamura/weneedfeed#29]
[YAML Aliases](https://blog.jasonhee.com/how-to-use-yaml-aliases) which are very helpful for repetitive selectors.

This [StackOverflow answer](https://stackoverflow.com/a/71192990/368328) explains some issues with Ruby 3.1.

As it stands, using a YAML Alias results in a incorrect config.

<details>
<summary>Broken YAML Config</summary>

```yml
&SELECTOR:
  item_selector: '#year2022 .pdf-item'
  item_description_selector: p
  item_link_selector: a:nth-child(1)
  item_title_selector: p:nth-child(2)
pages:
  - <<: *SELECTOR
    id: upi
    title: UPI Circulars
    description: NPCI UPI Circulars
    url: "https://www.npci.org.in/what-we-do/upi/circular"
  - <<: *SELECTOR
    id: cts
    title: CTS Circulars
    description: NPCI CTS Circulars
    url: "https://www.npci.org.in/what-we-do/cts/circulars"
```
</details>

**Comment by captn3m0** [comment]
I created this issue thinking aliases were working on Ruby 3.0, but it turns out they aren't - haven't checked why.

**Comment by r7kamura** [comment]
I decided to solve this problem by always using psych 4 or higher, then adding `aliases: true` option.

**Comment by captn3m0** [comment]
Slight difference in how it works, documenting in case it's helpful:

```yml
.common_selectors: &selector
  item_selector: '#year2022 .pdf-item'
  item_description_selector: p
  item_link_selector: a:nth-child(1)
  item_title_selector: p:nth-child(2)
pages:
  - <<: *selector
    id: upi
    title: UPI Circulars
    description: NPCI UPI Circulars
    url: "https://www.npci.org.in/what-we-do/upi/circular"
```
